name: cristo_em_mim_novo
description: Aplicativo oficial do projeto Cristo em Mim – Reflexões diárias de Ederson Rodrigues.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.0.10
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icone.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/livros/
    - assets/imagens/
    - assets/autor/foto.png
